### ISSUE TITLE
Update user..

### ISSUE THREAD

**Issue by bensquire** [wmluke/angular-bugsnag#13]
Hi!

Give that I won't be logged in when bugsnag is initially instantiated, how would I update the user property once the user has logged in?

Thanks
Ben

**Comment by bensquire** [comment]
I've got it... sorry.

**Comment by PazkaL** [comment]
could you give an example?

**Comment by bensquire** [comment]
@PazkaL We're using angularitcs so I don't think my eventual solution will help you:

$analytics.setUserProperties({name: 'foobar');
