### ISSUE TITLE
Dynamically Populate User Info

### ISSUE THREAD

**Issue by jwuliger** [wmluke/angular-bugsnag#20]
Hello,

I know that owners of this repo may be changing or have changed. I hate to ask but I am desperate. I am trying to find a way to populate the Bugsnag.user info based on a logged in user. Since that information is a provider and in the config, I am not sure how I can achieve that. Any help would be greatly appreciated. Thanks so much for your time.

**Comment by wmluke** [comment]
Hi @jwuliger,

You have several options...

#### 1. `bugsnagProvider.beforeNotify` accepts injectable parameters, so you can configure it too add you user info...

```js
bugsnagProvider
    .beforeNotify(['session', 'bugsnag', function (session, bugsnag) {
       return function (error, metaData) {
           // set your user 
           bugsnag.user = session.user;
           // set other runtime info
           metaData.account = session.accountInfo;
           return true;
       };
    }])
```

#### 2. `bugsnag` is injectable so you can set `bugsnag.user` whenever is necessary...

```js
module.run(['session', 'bugsnag', function(session, bugsnag){
   session.on('login', function(){
        bugsnag.user = session.user;
   });
}])
```

Good luck!

**Comment by jwuliger** [comment]
Thanks!

**Comment by kcampion** [comment]
Hi @wmluke,

Thank you for your examples.
But if you do that for **bugsnagProvider.beforeNotify**, you will have this mistake:
```
Uncaught Error: [$injector:cdep] Circular dependency found: bugsnag <- bugsnag
```

You can't use **bugsnag** as a parameter. The best way is to do this:
```javascript
bugsnagProvider
    .beforeNotify(['session', function (session) {
       return function (error, metaData) {
           // set your user 
           metaData.user = session.user;
           // set other runtime info
           metaData.account = session.accountInfo;
           return true;
       };
    }])
```
