### ISSUE TITLE
Angular Bugsnag is behind Bugsnag

### ISSUE THREAD

**Issue by bramski** [wmluke/angular-bugsnag#7]
Latest Angular Bugsnag depends on version
  ~ 2.3.5
Latest Bugnsag is
   ~ 2.4.6

This is forcing me to use an older version of bugsnag.  Can you guys please update & release?

**Comment by ivanbreet** [comment]
+1 
2.4.x added some awesome features.

**Comment by wmluke** [comment]
Just updated to to Bugsnag 2.4.7.
